In [1]:
import numpy as np

# Get data from array

Version 1

In [2]:
a = np.random.randint(0, 20,10)
a

array([ 7,  8,  9, 16, 13, 14, 17, 15, 12, 14])

Get all values >10

In [3]:
a[a > 10]

array([16, 13, 14, 17, 15, 12, 14])

### AND

In [4]:
a[(a > 10) & (a % 2 ==0)]

array([16, 14, 12, 14])

### OR

In [5]:
a[(a > 10) | (a % 3 == 0)]

array([ 9, 16, 13, 14, 17, 15, 12, 14])

### **numpy.where**

In [11]:
np.where(a > 10)   #  Results will be indexes of those values

(array([3, 4, 5, 6, 7, 8, 9]),)

In [12]:
a[np.where(a > 10)]   #  Results will be values > 10

array([16, 13, 14, 17, 15, 12, 14])

Version 2

In [13]:
a = [1,4,7]   # True, True, True
b = [9,2,5]   # Fale, False, False

In [14]:
# if True, element taken from a, else from b
np.where([True, False, True], a,b)

array([1, 2, 7])

# Sorting 

In [16]:
a = np.array([[1,3,9,0],
             [5,0,1,5],
             [2,7,3,5]])

In [17]:
# Swap row 2 with row 1 
a[[0,2,1], :]

array([[1, 3, 9, 0],
       [2, 7, 3, 5],
       [5, 0, 1, 5]])

In [18]:
a.argsort(axis = 0)

array([[0, 1, 1, 0],
       [2, 0, 2, 1],
       [1, 2, 0, 2]])

In [19]:
a[:,0].argsort()   #  Results indexes of Column [0]

array([0, 2, 1])

In [20]:
a[a[:,0].argsort(),:]

array([[1, 3, 9, 0],
       [2, 7, 3, 5],
       [5, 0, 1, 5]])

# shuffle randomly arrays 

In [22]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.random.shuffle(a)   #  without changing shape

In [24]:
a

array([1, 6, 8, 7, 5, 4, 0, 3, 9, 2])

### 2D arrays

In [25]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [26]:
np.random.shuffle(a)

In [31]:
a

array([[ 9, 10, 11],
       [ 6,  7,  8],
       [ 0,  1,  2],
       [ 3,  4,  5]])

# Mathematical procedures with arrays

In [32]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
# Get log of each value in array
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [34]:
# exhibitor
np.exp(a)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [35]:
# sum all values in array
a.sum()

21

In [36]:
# sum all values in each column
a.sum(axis = 0)

array([5, 7, 9])

In [37]:
# sum all values in each row
a.sum(axis = 1)

array([ 6, 15])

In [38]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
10 + a # Add 10 to each value of array

array([[11, 12, 13],
       [14, 15, 16]])

### multiply each value of one array into each value of another array

In [40]:
a = np.arange(12).reshape(3,-1)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
b = np.arange(12,24).reshape(-1, 4)
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [42]:
a * b

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

### Broadcasting

In [43]:
a = np.array([[2,5],[3,4],[6,1]])

In [44]:
b = np.array([1,2])

In [45]:
a + b

array([[3, 7],
       [4, 6],
       [7, 3]])

In [46]:
c = np.array([[1],[2],[3]])

In [47]:
a + c

array([[3, 6],
       [5, 6],
       [9, 4]])

### Static Functions

In [48]:
a = np.random.randint(0,12,(3,4))
a

array([[10,  8,  9,  3],
       [ 4,  0,  8,  5],
       [11, 11,  5,  7]])

In [49]:
a.min()

0

In [50]:
# min value from each column
a.min(axis = 0)

array([4, 0, 5, 3])

In [51]:
# max value from each row
a.max(axis = 1)

array([10,  8, 11])

In [52]:
# Average
a.mean(axis = 0)

array([8.33333333, 6.33333333, 7.33333333, 5.        ])

In [53]:
# arithmetic mean
a.std(axis = 0)

array([3.09120617, 4.64279609, 1.69967317, 1.63299316])

# Save and Read array from file

In [54]:
# Save into file a.npy array 'a'
np.save('a.npy', a)

In [55]:
# Read from file and store in variable 'b'
b = np.load('a.npy')

In [56]:
b

array([[10,  8,  9,  3],
       [ 4,  0,  8,  5],
       [11, 11,  5,  7]])