# Convertion

In [20]:
import numpy as np

Create a list 'a'

In [21]:
a = [i for i in range(10)]

In [22]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Create a tuple 'b'

In [23]:
b = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9)

Convert list and tuple into np.array

In [24]:
c = np.array(a)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
d = np.array(b)
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Types

Check np.array type:

In [26]:
type(d)

numpy.ndarray

Data types [ float32, float64, int32, int64 ] # 64 takes more space

In [ ]:
b = np.array([1., 2., 3.], dtype = np.float32) # Or float64

Create specific type np.array [int/float/str]

In [27]:
a = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9.9]

In [28]:
b = np.array(a, dtype = float)

In [29]:
b

array([0. , 1. , 2. , 3. , 4. , 5. , 6. , 7. , 8. , 9.9])

If change type of the list a to int, all values will become whole

In [30]:
b = np.array(a, dtype = int)

In [31]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
b = np.array(a, dtype = str)

In [33]:
b

array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9.9'], dtype='<U3')

# 2D array

In [35]:
b = np.array([
    [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], 
    [10, 11, 12, 13, 14, 15, 16, 17, 18, 19], 
    [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [36]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

Get shape & size

In [37]:
b.shape

(3, 10)

In [38]:
b.size

30

Get index

In [39]:
b[2,5]

25

Use slice

In [40]:
b[0:2, 0:3]

array([[ 0,  1,  2],
       [10, 11, 12]])

Create view  [ change 'c' this will effects 'b' ]

In [41]:
c = b[1:, 5:]

In [42]:
c

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

Maka a copy of np.array [Any changes on 'c' will not effects on 'b']

In [43]:
c = b[1:, 5:].copy()