In [1]:
import numpy as np

# Automatically creation of arrays

In [2]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
a = np.ones((5, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Arange(from, to, step)

In [8]:
np.arange(10)   #  value 'TO' is not included

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [7]:
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

### numpy.linspace(from, to, step)

In [11]:
np.linspace(0, 9.9, 100)   #  value 'TO' included

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

### numpy.logspace(from, to, qty)

In [13]:
np.logspace(0, 3, 4)   #  from 10**0, to 10**3, 4 values

array([   1.,   10.,  100., 1000.])

# Generate random numbers

### numpy.random.sample   #  random numbers from 0.0 to 1.0

In [15]:
np.random.sample()

0.7312668731602733

In [16]:
np.random.sample(3)   #  qty of value spread evenly between 0.0 and 1.0

array([0.94154714, 0.92541068, 0.35995473])

In [17]:
np.random.sample((2, 3))   #  2D array

array([[0.61540111, 0.81288609, 0.21919451],
       [0.07053785, 0.92757906, 0.47323346]])

In [21]:
np.random.sample((3, 6, 3))   #  3D array

array([[[0.3269926 , 0.7947119 , 0.71002536],
        [0.61020712, 0.82846193, 0.34508975],
        [0.44031003, 0.94826962, 0.36249122],
        [0.25674277, 0.00850375, 0.80572756],
        [0.71661187, 0.96849168, 0.82310826],
        [0.17657508, 0.31542086, 0.53553069]],

       [[0.39997017, 0.96575927, 0.32397385],
        [0.42555955, 0.81186923, 0.70778353],
        [0.9847514 , 0.00696405, 0.27049614],
        [0.84854534, 0.34984291, 0.65873812],
        [0.94985758, 0.80495443, 0.00539543],
        [0.97998767, 0.51956715, 0.52604858]],

       [[0.52764484, 0.91383227, 0.95047922],
        [0.33700278, 0.86112827, 0.10698033],
        [0.76558409, 0.31536385, 0.33740642],
        [0.67189645, 0.24865227, 0.90183772],
        [0.66335697, 0.76935844, 0.90190669],
        [0.0691033 , 0.94700149, 0.06360205]]])

### numpy.random.rand(qty)  

In [22]:
np.random.rand(10)   #  1D array

array([0.21853038, 0.70372623, 0.06466183, 0.74191286, 0.28379101,
       0.84940676, 0.95889938, 0.43366503, 0.25743299, 0.58443443])

In [23]:
np.random.rand(3, 4)   #  2D array

array([[0.49287148, 0.68470602, 0.94799084, 0.69212157],
       [0.27937353, 0.10455782, 0.51769724, 0.92069803],
       [0.22462039, 0.99206272, 0.83692633, 0.0333442 ]])

### numpy.random.randint   #  array from random whole numbers

In [24]:
np.random.randint(0, 100, 10)   #  (from, to, qty)

array([47, 91, 12, 12, 19, 74, 72,  1, 89, 48])

In [25]:
np.random.randint(0, 10, (3, 4))   #  (from, to, (array.shape))

array([[0, 8, 6, 7],
       [4, 2, 1, 3],
       [4, 3, 3, 3]])

### numpy.random.choice   #  get random value from array

In [27]:
b = np.array([1,5,2,7,3,8,6,4])
np.random.choice(b)

8

In [28]:
np.random.choice(b, 3)   #  (source, qty)

array([8, 4, 6])

### numpy.random.seed

In [29]:
np.random.seed(42)
np.random.randint(0,10,3)

array([6, 3, 7])

### reshape()   #  Change matrix shape

In [31]:
a = np.arange(12)   #  1D array
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [35]:
np.reshape(a,(3,4))  #  (source(rows, columns))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

When you don't know in how many columns to split

In [36]:
np.reshape(a,(3,-1))  #  (source(rows, columns = ?))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Resize Matrix

In [38]:
a.resize(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Flatten()

In [39]:
a = a.flatten()   #  From nD array into 1D array
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Concatenate Matrix vertically 

In [42]:
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [44]:
b = np.ones((2,3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [45]:
v = np.vstack((a, b))
v

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [46]:
a.shape, b.shape, v.shape

((2, 3), (2, 3), (4, 3))

Another way is to use concatenate()

In [47]:
np.concatenate((a,b), axis = 0)   #  0 - in vertical axis

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Concatenate Matrix horizontally

In [48]:
h = np.hstack((a,b))
h

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [49]:
a.shape, b.shape, v.shape

((2, 3), (2, 3), (4, 3))

Another way is to use concatenate()

In [50]:
np.concatenate((a,b), axis = 1)   #  1 - in horizontal axis

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

### Concatenate into a dimensional array 

In [51]:
d = np.dstack([a,b])
d

array([[[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]]])