In [32]:
import numpy as np

Create 2 vectors with same shape and size

In [33]:
a = np.array([0, 1, 2, 3, 4])

In [34]:
b = np.array([5, 6, 7, 8, 9])


# SUM of vectors

In [35]:
c = a + b # Must be the same size

In [36]:
c

array([ 5,  7,  9, 11, 13])

In [37]:
c = np.add(a, b)

In [38]:
c

array([ 5,  7,  9, 11, 13])

# SUBTRACT vectors

In [39]:
a = np.array([5, 4, 8, 4, 3])

In [40]:
b = np.array([3, 5, 7, 1, 3])

In [41]:
d = a - b # Must be the same size
d

array([ 2, -1,  1,  3,  0])

In [42]:
d = np.subtract(a, b)
d

array([ 2, -1,  1,  3,  0])

# MULTIPLICATION of the vectors by value

In [43]:
a = np.array([5, 4, 8, 4, 3])
a

array([5, 4, 8, 4, 3])

In [44]:
c = a * 2
c

array([10,  8, 16,  8,  6])

In [45]:
c = -10 * a
c

array([-50, -40, -80, -40, -30])

In [46]:
c = 0.5 * a
c

array([2.5, 2. , 4. , 2. , 1.5])

### Also another ways

In [47]:
a.dot(-10)

array([-50, -40, -80, -40, -30])

In [48]:
np.dot(-10, a)

array([-50, -40, -80, -40, -30])

In [49]:
np.multiply(-10, a)

array([-50, -40, -80, -40, -30])

# MULTIPLICATION of two vectors 

In [50]:
a = np.array([1, 2, 3])

In [51]:
b = np.array([4, 5, 6])

In [52]:
sp = a[0] * b[0] + a[1] * b[1] + a[2] * b[2]
sp

32

In [53]:
a @ b

32

In [54]:
sp = np.dot(a, b)
sp

32

# MATRIX

In [55]:
A = np.array([[0, 1], 
             [2, 3],
             [4, 5]])

In [56]:
B = np.array([[6, 7], 
             [8, 9],
             [10, 11]])

In [57]:
A.shape == B.shape

True

### Sum of Matrix

In [58]:
C = A + B
C

array([[ 6,  8],
       [10, 12],
       [14, 16]])

In [59]:
C = np.add(A, B)
C

array([[ 6,  8],
       [10, 12],
       [14, 16]])

### Substract Matrix

In [60]:
D = C - B
D

array([[0, 1],
       [2, 3],
       [4, 5]])

In [61]:
D = np.subtract(B, A)
D

array([[6, 6],
       [6, 6],
       [6, 6]])

### Multiplying Matrix and value

In [64]:
X = np.array([[1, 2], [3, 4]])
Y = X * 3
Y

array([[ 3,  6],
       [ 9, 12]])

In [65]:
Y = np.dot(X, 3)
Y

array([[ 3,  6],
       [ 9, 12]])

### Matrix multiplication       # !!! matrix A qty col == matrix B qty row !!!

In [66]:
X1 = np.array([[1, 2], [3, 4],[5, 6]])
X2 = np.array([[7, 8, 9, 10],[11, 12, 13, 14]])

In [68]:
X1.shape[1] == X2.shape[0] # Make sure this result is True !

True

In [69]:
X1.shape, X2.shape

((3, 2), (2, 4))

In [70]:
Z = np.dot(X1, X2)
Z

array([[ 29,  32,  35,  38],
       [ 65,  72,  79,  86],
       [101, 112, 123, 134]])

In [71]:
Z.shape

(3, 4)

### Matrix in power

In [74]:
A = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [75]:
A_square = np.dot(A, A)
A_square

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [78]:
A_square = np.linalg.matrix_power(A, 2)  #  !_power >= 0
A_square

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

### Identity Matrix

In [79]:
A = np.array([[1, 2], [3, 4],[5, 6]])
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

### Multiply Identity Matrix

In [80]:
np.dot(A, I)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [81]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [83]:
np.dot(I, A)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

### Transpose Matrix

In [85]:
A = np.array([[11, 13],[16, 9],[8, 15]])
At = A.transpose()   #   OR At = A.T
At

array([[11, 16,  8],
       [13,  9, 15]])

Where to use this?
Multiply Matrix X and Matrix Y impossible Because X.shape == Y.shape => False


In [86]:
X = np.array([[1,2],[3,4],[5,6]])
Y = np.array([[0,1],[3,4],[6,7],[2,5]])
X.shape == Y.shape

False

In [87]:
Yt = Y.T
Yt

array([[0, 3, 6, 2],
       [1, 4, 7, 5]])

In [88]:
np.dot(X, Yt)

array([[ 2, 11, 20, 12],
       [ 4, 25, 46, 26],
       [ 6, 39, 72, 40]])

### Matrix Rank

In [90]:
A = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [91]:
np.linalg.det(A)

0.0

In [92]:
np.linalg.matrix_rank(A)

2

### Inverse Matrix

In [93]:
B = np.array([[7, 4, 5], 
              [8, 3, 2],
              [6, 10, 12]])
B_inv = np.linalg.inv(B)
B_inv

array([[ 0.18604651,  0.02325581, -0.08139535],
       [-0.97674419,  0.62790698,  0.30232558],
       [ 0.72093023, -0.53488372, -0.12790698]])

If run again for B_inv will get first result

In [95]:
B_inv2 = np.linalg.inv(B_inv)
B_inv2

array([[ 7.,  4.,  5.],
       [ 8.,  3.,  2.],
       [ 6., 10., 12.]])